project_id = "nauwhubjoxeihxhmegjh"

[functions.process-notifications]
verify_jwt = false

[functions.audit-log]
verify_jwt = false

[functions.change-organization-plan]
verify_jwt = false

[functions.create-organization]
verify_jwt = false

[functions.accept-invite]
verify_jwt = false
