project_id = "nauwhubjoxeihxhmegjh"

[functions.process-notifications]
verify_jwt = false

[functions.audit-log]
verify_jwt = false

[functions.change-organization-plan]
verify_jwt = false

[functions.create-organization]
verify_jwt = false

[functions.accept-invite]
verify_jwt = false

[functions.update-organization]
verify_jwt = false

[functions.reset-owner-password]
verify_jwt = false

[functions.manage-user]
verify_jwt = false

[functions.update-role-permissions]
verify_jwt = false

[functions.delete-organization]
verify_jwt = false
